server/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.user_list, name='user_list'),
    path('<int:user_pk>/', views.profile, name='profile'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('follow/<int:person_pk>/', views.follow, name='follow'),
]

server/movierec/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as accounts_views
from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('api-token-verify/', obtain_jwt_token),
    path('api/v1/movies/', include('movies.api_urls')),
    path('api/v1/users/', include('accounts.api_urls')),
    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls')),
]

server/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:movie_pk>/', views.detail, name='detail'),
    path('detail/<int:movie_pk>/review/new/', views.review_new, name='review_new'),
    path('detail/<int:movie_pk>/review/<int:review_pk>/', views.review_delete, name='review_delete'),
    path('detail/<int:movie_pk>/like/', views.like, name='like'),
]

server/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings', blank=True)

server/movies/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

# Create your models here.
class Genre(models.Model):
    name = models.TextField(max_length=20)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    poster_url = models.CharField(max_length=140)
    description = models.TextField()
    genres = models.ManyToManyField(Genre, related_name='movies')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies', blank=True)

    def get_absolute_url(self):
        return reverse('movies:detail', kwargs={'movie_pk': self.pk})

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ('-pk',)


class Review(models.Model):
    content = models.CharField(max_length=140)
    score = models.FloatField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

server/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('email',)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name')

server/movies/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('content', 'score', )

    content = forms.CharField(
        label='리뷰 작성하기',
        max_length=140,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control review-content',
                'placeholder': '리뷰 내용을 입력해주세요.',
                'rows': 4,
            }
        )
    )

server/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.views.decorators.http import require_POST
from .forms import CustomUserChangeForm, CustomUserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import get_user_model

def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/auth_form.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/auth_form.html', context)


def logout(request):
    auth_logout(request)
    return redirect('movies:index')


@require_POST
def delete(request):
    request.user.delete()
    return redirect('movies:index')


def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
        context = {
            'form': form,
        }
        return render(request, 'accounts/auth_form.html', context)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/auth_form.html', context)


def profile(request, user_pk):
    User = get_user_model()
    person = get_object_or_404(User, pk=user_pk)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)
    

def follow(request, person_pk):
    User = get_user_model()
    person = get_object_or_404(User, pk=person_pk)
    user = request.user
    if person.followers.filter(pk=user.pk).exists():
        person.followers.remove(user)
    else:
        person.followers.add(user)
    return redirect('accounts:profile', person.pk)


def user_list(request):
    User = get_user_model()
    users = User.objects.all()
    context = {
        'users': users,
    }
    return render(request, 'accounts/user_list.html', context)

server/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie, Review
from .forms import ReviewForm
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    context = {
        'movies': Movie.objects.all(),
    }
    return render(request, 'movies/index.html', context)


def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    review_form = ReviewForm()
    context = {
        'movie': movie,
        'form': review_form,
        'reviews': movie.review_set.all(),
    }
    return render(request, 'movies/detail.html', context)


@login_required
@require_POST
def review_new(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.movie = movie
            review.user = request.user
            review.save()
    return redirect(movie)


@login_required
def review_delete(request, movie_pk, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.user == review.user:
        review.delete()
    return redirect('movies:detail', movie_pk)


@login_required
def like(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    user = request.user
    # 만약 좋아요 리스트에 현재 접속중인 유저가 있다면, Unlike 처리
    if movie.like_users.filter(pk=user.pk).exists():
        movie.like_users.remove(user)
    else:
        movie.like_users.add(user)
    return redirect(movie)

server/accounts/templates/accounts/auth_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
{% if request.resolver_match.url_name == 'signup' %}
  <h1>회원가입</h1>
{% elif request.resolver_match.url_name == 'login' %}
  <h1>로그인</h1>
{% elif request.resolver_match.url_name == 'update' %}
  <h1>회원정보 수정</h1>
{% else %}
  <h1>비밀번호 변경</h1>
{% endif %}

<form method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons submit="제출하기" %}{% endbuttons %}
</form>
{% endblock %}

server/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
  {% with followers=person.followers.all followings=person.followings.all %}
    {% if user != person %}
      {% if user in followers %}
        <a href="{% url 'accounts:follow' person.pk %}" class="btn btn-outline-primary d-block">Unfollow</a>
      {% else %}
        <a href="{% url 'accounts:follow' person.pk %}" class="btn btn-primary d-block">Follow</a>
      {% endif %}
    {% endif %}
    <h1 class="text-center mt-3 mb-5">{{ person }}</h1>
    <h2>팔로워</h2>
    <p>팔로워 수: {{ followers|length }}</p>
  
    <h2 class="mt-5">팔로잉</h2>
    <p>팔로잉 수: {{ followings|length }}</p>
  {% endwith %}

  <h2 class="mt-5">좋아요 목록</h2>
  {% for movie in person.like_movies.all %}
    <p><a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a></p>
  {% endfor %}

  <h2 class="mt-5">리뷰 목록</h2>
  {% for review in person.review_set.all %}
    <p><a href="{% url 'movies:detail' review.movie.pk %}">{{ review.movie.title }}</a> | {{ review.score }} | {{ review.content }}</p>
  {% endfor %}
{% endblock %}

server/accounts/templates/accounts/user_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
  <h1 class="text-center my-5">사용자 목록</h1>
  {% for user in users %}
    <p>{{ user.pk }} | <a href="{% url 'accounts:profile' user.pk %}">{{ user.username }}</a></p>
  {% endfor %}
{% endblock %}

server/movierec/templates/base.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<!DOCTYPE html>
<html lang="kr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Movie</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'movies:index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
          <li class="nav-item active"><a href="{% url 'accounts:user_list' %}" class="btn btn-light">사용자목록</a></li>
        {% if user.is_authenticated %}
          <li class="nav-item active"><a href="{% url 'accounts:logout' %}" class="btn btn-danger">로그아웃</a></li>
          <li class="nav-item active"><a href="{% url 'accounts:update' %}" class="btn btn-success">회원정보수정</a></li>
        {% else %}
          <li class="nav-item active"><a href="{% url 'accounts:signup' %}" class="btn btn-dark">회원가입</a></li>
          <li class="nav-item active"><a href="{% url 'accounts:login' %}" class="btn btn-dark">로그인</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
</body>
</html>

server/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
  <h1 class="text-center font-weight-bold">{{ movie.title }}</h1>
  <div class="text-center">
    {% for genre in movie.genres.all %}
      <span class="btn btn-dark">{{ genre }}</span>
    {% endfor %}
  </div>
  <div class="mt-3 text-center">
    <img src="{{ movie.poster_url }}" style="height: 500px;">
    
  </div>
  <br>
  <br>
  <label>누적관객수</label>
  <p class="form-control">{{ movie.audience }}</p>
  <label>줄거리</label>
  <div>
    <span>{{ movie.description }}</span>
  </div>
  <br>
  <form action="{% url 'movies:review_new' movie.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-success">등록하기</button>
  </form>
  <br>
  {% for review in reviews %}
    <p>평점: {{ review.score }}&#9;|&#9;{{ review.content }}&#9;<a href="{% url 'movies:review_delete' movie.pk review.pk %}" class="btn-sm btn-danger">삭제</a></p>
  {% endfor %}

  {% if request.user in movie.like_users.all %}
    <a href="{% url 'movies:like' movie.pk %}" class="btn-sm btn-outline-danger mt-5 d-block text-center">좋아요 취소</a>
  {% else %}
    <a href="{% url 'movies:like' movie.pk %}" class="btn-sm btn-danger mt-5 d-block text-center">좋아요</a>
  {% endif %}
  
  <a href="{% url 'movies:index' %}" class="btn btn-dark d-block">목록으로</a>
{% endblock %}

server/movies/templates/movies/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
<h1 class="text-center my-5">INDEX</h1>  
  <div class="row justify-content-center">  
    {% for movie in movies %}
      <div class="card border-dark m-3" style="width: 18rem;">
        <a href="{% url 'movies:detail' movie.pk %}"><img src="{{ movie.poster_url }}" class="card-img-top"></a>
        <div class="card-body text-center border-dark">
          <h5 class="card-title">{{ movie.title }}</h5>
            {% for genre in movie.genres.all %}
              <span class="btn-sm btn-dark">{{ genre }}</span>
            {% endfor %}
          </h6>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}