project_10/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:movie_pk>/', views.detail, name='detail'),
    path('detail/<int:movie_pk>/review/new/', views.review_new, name='review_new'),
    path('detail/<int:movie_pk>/review/<int:review_pk>/', views.review_delete, name='review_delete'),
]

project_10/movies/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

# Create your models here.
class Genre(models.Model):
    name = models.TextField(max_length=50)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=100)
    audience = models.IntegerField()
    poster_url = models.TextField()
    description = models.TextField()
    genres = models.ManyToManyField(Genre, related_name='movies')

    def get_absolute_url(self):
        return reverse('movies:detail', kwargs={'movie_pk': self.pk})

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ('-pk',)


class Review(models.Model):
    content = models.TextField()
    score = models.FloatField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

project_10/movies/forms.py
from django import forms
from .models import Movie, Review, Genre


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('content', 'score', )

    content = forms.CharField(
        label='리뷰 작성하기',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control review-content',
                'placeholder': '리뷰 내용을 입력해주세요.',
                'rows': 4,
            }
        )
    )

project_10/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie, Review
from .forms import ReviewForm
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    context = {
        'movies': Movie.objects.all(),
    }
    return render(request, 'movies/index.html', context)


def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    # 직접 만들어 보기
    review_form = ReviewForm()
    context = {
        'movie': movie,
        'form': review_form,
        'reviews': movie.review_set.all(),
    }
    return render(request, 'movies/detail.html', context)


# @login_required
# @require_POST
def review_new(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.movie = movie
            # movie.user = request.user
            review.save()
    return redirect(movie)


# @require_POST
# @login_required
def review_delete(request, movie_pk, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.method == 'POST':
        review.delete()
    return redirect('movies:detail', movie_pk)

project_10/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
  <h1 class="text-center font-weight-bold">{{ movie.title }}</h1>
  <div class="text-center">
    {% for genre in movie.genres.all %}
      <span class="btn btn-dark">{{ genre }}</span>
    {% endfor %}
  </div>
  <div class="mt-3 text-center">
    <img src="{{ movie.poster_url }}" style="height: 500px;">
    
  </div>
  <br>
  <br>
  <label>누적관객수</label>
  <p class="form-control">{{ movie.audience }}</p>
  <label>줄거리</label>
  <div>
    <span>{{ movie.description }}</span>
  </div>
  <br>
  <form action="{% url 'movies:review_new' movie.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-success">등록하기</button>
  </form>
  <br>
  {% for review in reviews %}
    <p>평점: {{ review.score }}&#9;|&#9;{{ review.content }}&#9;<a href="{% url 'movies:review_delete' movie.pk review.pk %}" class="btn-sm btn-danger">삭제</a></p>
  {% endfor %}
  <a href="" class="btn-sm btn-danger mt-5 d-block text-center">좋아요</a>
  <a href="{% url 'movies:index' %}" class="btn btn-dark d-block">목록으로</a>
{% endblock %}